apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: studtarasov
  annotations:
    description: "Service for deployment of the mlflow"
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    name: mlflow