default:
  tags:
    - python

stages:
  - deploy

image: pytorch/pytorch:latest

make_experiments:
  stage: deploy
  variables:
    PYTHONUNBUFFERED: 1
    PYTHONDONTWRITEBYTECODE: 1
    PIP_NO_CACHE_DIR: "off"
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_DEFAULT_TIMEOUT: 100
  script:
    - echo "CI/CD is replaced to the docker-compose"