default:
  tags:
    - ssh
    - coder

stages:
  - build

docker_image:
  stage: build
  before_script:
    - bash ./backend/ml/deployment/before_script.sh
  script:
    - bash ./backend/ml/deployment/main_script.sh
  after_script:
    - bash ./backend/ml/deployment/after_script.sh