default:
  tags:
    - ssh

stages:
  - build

graph_learning_workbench:
  stage: build
  environment:
    name: production
    url: http://34.159.70.187:8000/
  before_script:
    - bash ./backend/ml/deployment/production/before_script.sh
  script:
    - bash ./backend/ml/deployment/production/main_script.sh
  after_script:
    - bash ./backend/ml/deployment/production/after_script.sh
  only:
    refs:
      - main
    changes:
      - .gitlab-ci.yml
      - backend/ml/deployment/production/Dockerfile
      - "**/**/**/**/**/*.yaml"
      - "**/**/**/**/**/**/*.yaml"
      - "**/**/**/*.py"
      - "**/**/**/**/*.sh"