default:
  tags:
    - ssh

stages:
  - build

graph_learning_workbench:
  stage: build
  before_script:
    - bash ./backend/ml/deployment/before_script.sh
  script:
    - bash ./backend/ml/deployment/main_script.sh
  after_script:
    - bash ./backend/ml/deployment/after_script.sh
  only:
    refs:
      - main
    changes:
      - .gitlab-ci.yml
      - backend/ml/deployment/Dockerfile
      - "**/**/**/*.py"
      - "**/**/**/**/*.py"
      - "**/**/**/*/sh"
      - backend/ml/deployment/kubernates.yaml