default:
  tags:
    - ssh

stages:
  - build

graph_learning_workbench:
  stage: build
  environment:
    name: production
  before_script:
    - bash ./backend/ml/deployment/production/before_script.sh
  script:
    - bash ./backend/ml/deployment/production/main_script.sh
  after_script:
    - bash ./backend/ml/deployment/production/after_script.sh
  only:
    changes:
      - .gitlab-ci.yml
      - backend/ml/deployment/production/Dockerfile
      - backend/ml/deployment/production/kubernates.yaml
      - "**/**/**/*.py"
      - "**/**/**/**/*.sh"