default:
  tags:
    - python

stages:
  - build

docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script: cd backend/ml && docker build -t $UNI_DOCKER_REGISTRY .