apiVersion: v1
kind: Service
metadata:
  name: graph-learning-workbench-service
  namespace: studtarasov
  annotations:
    description: "Service for deployment of the graph learning workbench"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    name: graph-learning-workbench