apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graph-learning-workbench
  namespace: studtarasov
  annotations:
    description: "Deployment of the graph learning workbench"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: graph-learning-workbench
    spec:
      containers:
      - resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "8"
            memory: "16Gi"
          requests:
            nvidia.com/gpu: "1"
            cpu: "4"
            memory: "8Gi"
        name: graph-learning-workbench
        image: ls6-stud-registry.informatik.uni-wuerzburg.de/studtarasov/graph_learning_workbench:0.0.1
        imagePullPolicy: Always
        command: ["gunicorn", "--bind", "0.0.0.0:9000", "main:app"]
        ports:
        - name: http
          containerPort: 9000
        volumeMounts:
          - mountPath: /workspace
            name: project-code
      imagePullSecrets:
      - name: lsx-registry
      volumes:
        - name: project-code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studtarasov
            path: "/home/stud/tarasov/xtai_lab3/application"
            secretRef:
              name: ceph-secret
---
apiVersion: v1
kind: Service
metadata:
  name: graph-learning-workbench-service
  namespace: studtarasov
  annotations:
    description: "Service for deployment of the graph learning workbench"
spec:
  type: NodePort
  ports:
  - port: 9000
  selector:
    name: graph-learning-workbench